### ISSUE TITLE
page.js里的数据如何渲染到hbs页面中

### ISSUE THREAD

**Issue by dzhmoper** [cloud-templates/jQuery-template#1]
请教一下，各页面page.js里的数据如何渲染到hbs页面中?

**Comment by cklwblove** [comment]
@dzhmoper 模板更新了下，添加了一个 page.js 的数据渲染到 hbs 页面的示例。可以参考 [demo](https://github.com/cloud-templates/jQuery-template/tree/master/template/src/pages/index)  里的 [order.tpl.hbs](https://github.com/cloud-templates/jQuery-template/blob/43cd06d55e94071cb17b3b4a60e53dce4a65c5e3/template/src/pages/index/order.tpl.hbs#L1) 及 [page.js。](https://github.com/cloud-templates/jQuery-template/blob/43cd06d55e94071cb17b3b4a60e53dce4a65c5e3/template/src/pages/index/page.js#L20)
